services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ppdb_smk_bani_masum
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    env_file:
      - .env.local
